// Copyright 2022, the Chromium project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAR1iqVXIw2O1USH7LBgzPN4Y22GnDlwhw",
    authDomain: "messageapp-ec791.firebaseapp.com",
    projectId: "messageapp-ec791",
    storageBucket: "messageapp-ec791.appspot.com",
    messagingSenderId: "264386057956",
    appId: "1:264386057956:web:fb9970ff981502e4357ef1",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSBaZ1rTRfpio42u_TctiebcmUltx58Os',
    appId: '1:264386057956:android:b71715d9fe02342f357ef1',
    messagingSenderId: '264386057956',
    projectId: 'messageapp-ec791',
    // databaseURL:
    //     'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'messageapp-ec791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLDkvlRZNl7jbtLe90KOsDvnKchROI0h0',
    appId: '1:264386057956:ios:c9b80b2adb35269d357ef1',
    messagingSenderId: '264386057956',
    projectId: 'messageapp-ec791',
    // databaseURL:
    //     'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'messageapp-ec791.appspot.com',
    // androidClientId:
    //     '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
    // iosClientId:
    //     '406099696497-584r3j0bb2to4prgnjj2nfn1or1pqqbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageapp',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDooSUGSf63Ghq02_iIhtnmwMDs4HlWS6c',
  //   appId: '1:406099696497:ios:6327d2773542b6053574d0',
  //   messagingSenderId: '406099696497',
  //   projectId: 'flutterfire-e2e-tests',
  //   databaseURL:
  //       'https://flutterfire-e2e-tests-default-rtdb.europe-west1.firebasedatabase.app',
  //   storageBucket: 'flutterfire-e2e-tests.appspot.com',
  //   androidClientId:
  //       '406099696497-17qn06u8a0dc717u8ul7s49ampk13lul.apps.googleusercontent.com',
  //   iosClientId:
  //       '406099696497-584r3j0bb2to4prgnjj2nfn1or1pqqbg.apps.googleusercontent.com',
  //   iosBundleId: 'io.flutter.plugins.firebase.analytics.example',
  // );
}
